nama = input (" nama lengkap : ")
panggilan = input (' nama panggilan : ')
ttl = input (' tempat dan tanggal lahir: ')
umur = input (' umur: ')
alamat = input (' alamat: ')
namauniversitas = input (' nama universitas: ')
nim = input (' nim: ')
prodi = input (' prodi: ')
nohp = input (' no hp: ')
print (" jadi nama lengkap saya adalah ",nama," nama panggilan saya ",panggilan,"tempat dan tanggal lahir saya ",ttl)
print (" umur saya ",umur," alamat saya ada di ",alamat," saya berkuliah di ",namauniversitas)
print (" nim saya ",nim," prodi saya ",prodi," no hp saya ",nohp) 
